#!/bin/sh

# PROVIDE: ttrss
# REQUIRE: NETWORKING
# REQUIRE: DAEMON mysql
# BEFORE: LOGIN
# KEYWORD: shutdown

# RC-TTRSS TTRSS Updater rc script
# Copyright (c) 2016, Zerotronic
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

. /etc/rc.subr

name=ttrss
rcvar=`set_rcvar`
phpexec=`which php`
start_precmd="${name}_prestart"
start_cmd="${name}_start"
stop_cmd="${name}_stopcmd"
stop_postcmd="${name}_cleanup"

: ${ttrss_user:="root"}
: ${ttrss_cmd_user:="ttrss"}
: ${ttrss_dir:="/usr/local/www/apache24/data/tt-rss"}
: ${ttrss_pid:="/var/run/ttrss.pid"}
: ${ttrss_log:="/var/log/ttrss-log"}
: ${ttrss_enable:="NO"}

command_args=${ttrss_dir}/update_daemon2.php
command=/usr/sbin/daemon
procname=${name}
pidfile=${ttrss_pid}
required_files="${ttrss_dir}/update_daemon2.php"

ttrss_prestart()
{
	touch ${ttrss_log} && chown ${ttrss_cmd_user} ${ttrss_log}
	touch ${ttrss_pid} && chown ${ttrss_cmd_user} ${ttrss_pid}
}

ttrss_start()
{
	echo "Starting ttrss-update-daemon"
	exec ${command} -c -t ${name} -P ${ttrss_pid} -u ${ttrss_cmd_user} ${phpexec} ${command_args} > ${ttrss_log}
}

ttrss_stopcmd()
{
	if [ -f "${ttrss_pid}" ] && (pgrep -F ${ttrss_pid} daemon > /dev/null); then
		main_pid=$(cat ${ttrss_pid});
		child_pids=$(pgrep -P ${main_pid});
		grandchild_pids=$(pgrep -P ${child_pids});
		all_pids="${main_pid} ${child_pids}";
		all_pids_with_grandchildren="${main_pid} ${child_pids} ${grandchild_pids}";
		kill ${all_pids};
		wait_for_pids ${all_pids_with_grandchildren};
		rm -rf ${ttrss_pid};
	else
		echo "${name} is not running.";
		exit 1;
	fi
}

ttrss_cleanup()
{
	echo "Cleaning up after ttrss-update-daemon..."
	if [ -f ${ttrss_pid} ]; then
		rm -rf ${ttrss_pid}
	fi
	if [ -f ${ttrss_dir}/lock/update_daemon.lock ]; then
		rm -rf ${ttrss_dir}/lock/update_daemon*.lock
	fi
}

load_rc_config ${name}
run_rc_command "$1"
