#!/bin/sh

# PROVIDE: ttrss
# REQUIRE: NETWORKING 
# REQUIRE: DAEMON mysql
# BEFORE: LOGIN
# KEYWORD: shutdown

# RC-TTRSS TTRSS Updater rc script
# Copyright (c) 2016, Zerotronic
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

. /etc/rc.subr

name=ttrss
rcvar=`set_rcvar`
phpexec=`which php`
start_precmd="${name}_precmd"
start_cmd="${name}_start"
stop_postcmd="${name}_cleanup"
load_rc_config ${name}

: ${ttrss_user:="ttrss"}
: ${ttrss_dir:="/usr/local/www/apache24/data/tt-rss"}
: ${ttrss_pid:="/var/run/ttrss.pid"}

command=${phpexec}
standalone=${ttrss_dir}/update_daemon2.php

ttrss_precmd()
{
	if [ -f ${ttrss_dir}/lock/update_daemon.lock ]; then
		rm -rf ${ttrss_dir}/lock/update_daemon*.lock
	fi
	touch /var/log/ttrss-log
}

ttrss_start()
{
	echo "Starting ttrss-update-daemon"
	touch ${ttrss_pid} && chown ${ttrss_user} ${ttrss_pid}
	exec /usr/sbin/daemon -c -p ${ttrss_pid} -u ${ttrss_user} ${standalone} > /var/log/ttrss-log
}

ttrss_cleanup()
{
	[ -f ${ttrss_pid} ] && rm ${ttrss_pid}
}

run_rc_command "$1"
